version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ${HOME}/.env:/root/.env:ro
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    command: ["--help"]
    entrypoint: ["/go/bin/githubcli"]
    tty: true
    stdin_open: true

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ${HOME}/.env:/root/.env:ro
      - go-modules:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    entrypoint: ["/bin/sh", "-c"]
    command: "apk add --no-cache git && go install github.com/cosmtrek/air@latest && air -c .air.toml"
    tty: true
    stdin_open: true

volumes:
  go-modules:
  go-build-cache:
